name: kiosk_debug_tool
description: Administrator tool for debugging and controlling RCV Kiosk machines
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_animate: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/RCV.png"
  adaptive_icon_background: "#005440"
  adaptive_icon_foreground: "assets/RCV.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
