// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtqyWMTneoeZfpG0b4EJ-m4jspcAOrmg',
    appId: '1:626543264813:web:3f246256e1a6ad1887a4a4',
    messagingSenderId: '626543264813',
    projectId: 'rcv-flutterfire',
    authDomain: 'rcv-flutterfire.firebaseapp.com',
    storageBucket: 'rcv-flutterfire.firebasestorage.app',
    measurementId: 'G-YQMGB9WJ3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9T-bGPQsaEhVJq_bldtJThGfJ6zO5V4',
    appId: '1:626543264813:android:24cf510139e3687287a4a4',
    messagingSenderId: '626543264813',
    projectId: 'rcv-flutterfire',
    storageBucket: 'rcv-flutterfire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wo86SphkMAn5oIDLWn9cuA6lwmfvirE',
    appId: '1:626543264813:ios:891b238c49aed4b587a4a4',
    messagingSenderId: '626543264813',
    projectId: 'rcv-flutterfire',
    storageBucket: 'rcv-flutterfire.firebasestorage.app',
    iosBundleId: 'com.example.rcvFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjtqyWMTneoeZfpG0b4EJ-m4jspcAOrmg',
    appId: '1:626543264813:web:c993ba6d4ac0a3a787a4a4',
    messagingSenderId: '626543264813',
    projectId: 'rcv-flutterfire',
    authDomain: 'rcv-flutterfire.firebaseapp.com',
    storageBucket: 'rcv-flutterfire.firebasestorage.app',
    measurementId: 'G-LKZVF2LV94',
  );

}