name: Flutter Build Check

# Trigger the workflow on Pull Requests to main or development
on:
  push:
    branches:
      - main
      - development
      - 'feature/**' 
      - 'bugfix/**'
  pull_request:
    branches:
      - main
      - development

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Setup Java (Required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create dummy .env file
        run: touch .env
        working-directory: ./app/rcv_firebase

      # 4. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./app/rcv_firebase

      # 5. Check for formatting and static analysis errors (Optional but recommended)
      - name: Run Analyzer
        run: flutter analyze
        working-directory: ./app/rcv_firebase

      # 6. Build APK (only on main branch)
      - name: Build APK
        if: github.ref == 'refs/heads/main'
        run: flutter build apk --release
        working-directory: ./app/rcv_firebase

      # 7. Upload to Firebase App Distribution (only on main branch)
      - name: Upload to Firebase App Distribution
        if: github.ref == 'refs/heads/main'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/rcv_firebase/build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Automated build from commit ${{ github.sha }}"